config/routes.rb
Rating::Application.routes.draw do
  resources :firms











end

app/models/firm.rb
class Firm < ActiveRecord::Base
  has_many :Recommendations
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :Firm
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # added some comments to app controller
  #more comments
  #one more comment
end

app/controllers/firms_controller.rb
#encoding: utf-8

class FirmsController < ApplicationController
  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all
    @firm = Firm.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @firms }
    end
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
    @firm = Firm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @firm }
    end
  end

  # GET /firms/new
  # GET /firms/new.json
  def new
    @firm = Firm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @firms }
    end

  end

  # GET /firms/1/edit
  def edit
    @firm = Firm.find(params[:id])
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(params[:firm])

    respond_to do |format|
      if @firm.save
        #format.html { redirect_to @firm, notice: 'Хуясе, новую фирму добавили в натуре' }
        #format.json { render json: @firm, status: :created, location: @firm }
        format.html { redirect_to firms_url }
        format.js
        #format.json { head :ok }
      else
        format.html { render action: "new" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /firms/1
  # PUT /firms/1.json
  def update
    @firm = Firm.find(params[:id])

    respond_to do |format|
      if @firm.update_attributes(params[:firm])
        @recommend = Recommendation.new()
        @recommend.rating = params[:rating]
        @firm.Recommendations << @recommend
        if @recommend.save
          format.html { redirect_to @firm, notice: '' }
          format.json { head :ok }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm = Firm.find(params[:id])
    @nametodel = @firm.name
    @firm.destroy

    respond_to do |format|
      format.html { redirect_to firms_url }
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/views/firms/_firm2.html.erb
<li><%= link_to cc.name, :action => 'edit', :id => cc.id %> <%= link_to "Накуй его", cc, method: :delete, :remote => true, :id => cc.id %> </li>

app/views/firms/_form.html.erb
<%= form_for @firm, :remote => true do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> никуя не получилось сохранить в базе:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Добавляй уже нах' %>
  </div>
<% end %>

app/views/firms/_form2.html.erb
<%= form_for(@firm) do |f| %>
  <% if @firm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@firm.errors.count, "error") %> prohibited this firm from being saved:</h2>

      <ul>
      <% @firm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= radio_button_tag(:rating, 5) %>
  <%= label_tag(:recommend_5, "Ахуительно") %>
  <br>
  <%= radio_button_tag(:rating, 4) %>
  <%= label_tag(:recommend_4, "Пиздато") %>
  <br>
  <%= radio_button_tag(:rating, 3) %>
  <%= label_tag(:recommend_4, "Хуеватенько") %>
  <br>
  <%= radio_button_tag(:rating, 2) %>
  <%= label_tag(:recommend_4, "Уебищно") %>
  <br>
  <%= radio_button_tag(:rating, 1) %>
  <%= label_tag(:recommend_4, "Ни в пизду, ни в Красную Армию") %>
  <br>

  <div class="actions">
    <%= f.submit 'Я так думаю!' %>
  </div>
<% end %>

app/views/firms/create.js.erb
$("#subject_list").append('<%= render 'firm2', :cc=>@firm %>')

app/views/firms/destroy.js.erb
$("li").remove(":contains(<%=@nametodel%>)");

app/views/firms/edit.html.erb
<h1>Пожалуйста, будте так добры потрудиться оценить качество выполненных работ:</h1>

<%= render 'form2' %>

<%= link_to 'Назад нах', firms_path %>

app/views/firms/index.html.erb
<h1>Список фирм-исполнителей епта</h1>



<ul id="subject_list">
<% @firms.each do |c| %>

<!-- <li><%= link_to c.name, :action => 'edit', :id => c.id %> <%= link_to "Накуй его", c, method: :delete, :id => c.id %></li>    -->
<%= render 'firm2', :cc=>c %>

<% end %>
</ul>

<br />

<%= render 'form'  %>

app/views/firms/new.html.erb
<h1>Новаго испалнителя пеши сюда:</h1>

<%= render 'form' %>

<%= link_to 'Назад нах', firms_path %>

app/views/firms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @firm.name %>
</p>


<%= link_to 'Назад нах', firms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= javascript_include_tag :defaults %>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>